language: python
env:
    - DJANGO_SETTINGS_MODULE=concordia.settings_test
dist: xenial
sudo: required
addons:
    sonarcloud:
        organization: 'libraryofcongress'
python:
    - '3.6'
    - '3.7'
    - '3.7-dev'
    - '3.8-dev'
matrix:
    allow_failures:
        - python: 3.7-dev
        - python: 3.8-dev
services:
    - postgresql
before_script:
    - psql -c 'create database concordia;' -U postgres
install:
    - pip install --upgrade pip
    # We install pre-commit outside of the virtualenv to avoid issues with pipenv / pip
    # in the Travis CI Python 3.6 environment. Once we upgrade to Python 3.7 this will
    # no longer be necessary:
    - pip install coveralls "pipenv>=2018.11.26" pre-commit safety
    - pipenv install --dev --deploy
script:
    - mkdir logs
    - touch ./logs/concordia-celery.log
    - ./manage.py collectstatic --no-input
    - ./manage.py test concordia importer exporter
    - coverage run ./manage.py test concordia importer exporter
    - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs pre-commit run --files
    - safety check
    - sonar-scanner -Dsonar.projectKey=libraryofcongress_concordia -Dsonar.organization=libraryofcongress -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io
after_success:
    - coveralls
