# Generated by Django 2.2b1 on 2019-02-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concordia", "0025_auto_20190221_1148"),
        ("concordia", "0024_auto_20190211_1420"),
    ]

    operations = []
